### ISSUE TITLE
de l'importance de la rigueur et de la cohérence dans la rédaction de documents techniques à l'usage des frabricants de sites internet, étude de l'influence du casse-couilles notoire dans la capacité de l'équipe technique à résoudre les problèmes de cohérence rencontrés lors de la réalisation de sites Internet

### ISSUE THREAD

**Issue by metallou** [simplonmars3/SimplonStrap#17]
Heu
.test-left, .tl, .lefttt
{
  text-align: right;;
}
Y'a pas un truc qui vous choque ? (autre que le double semi-colon)
(idem pour .text-right, .tr, .righttt)

**Comment by GLoSL** [comment]
https://github.com/simplonmars3/SimplonStrap/issues/15

**Comment by GLoSL** [comment]
Sinon ça va le titre ? ^^

**Comment by metallou** [comment]
oui (j'ai mis plus de temps pour le titre que pour le texte)
