### ISSUE TITLE
code???

### ISSUE THREAD

**Issue by GuillotJessica** [simplonmars3/SimplonStrap#2]
c'est quoi code ligne 215-219?

**Comment by GuillotJessica** [comment]
ligne 252 il y a .nav ? alors que nav est une balise elle même
promis je lirais pas tout le fichier ce soir

**Comment by Darkilen** [comment]
La balise <code> est une balise html, elle permet (comme dans la doc) de présenter du code qui n'est pas exécuté. 
Ex : http://41mag.fr/liste-des-balises-html5/balise-code-html5

Quant à la classe .nav c'est au cas où tu utilises une autre balise (pas recommandé) mais que tu souhaites quand même avoir le comportement d'une <nav>.

**Comment by valdiss** [comment]
Jessica, .nav c'est pour styliser ta nav comme la nôtre, tu as juste a ajouter cette classe a ta balise nav (ou div). Lis la doc.

On a créé une classe .nav au lieu de le mettre directement sur le sélecteur de balise nav pour que tu ne sois pas obligée d'avoir une nav préformatée, si tu veux deux nav différentes par exemple, ou même si tu veux profiter des autres avantages du framework mais pas la nav que tu trouve moche.

**Comment by GuillotJessica** [comment]
Je fais des pull request et des issues parce qu'ils njjous l'ont demandé
ils auront des trucs a dire lundi
Tcho

Le 30 nov. 2016 14:37, "valdiss" <notifications@github.com> a écrit :

Jessica, .nav c'est pour styliser ta nav comme la nôtre, tu as juste a
ajouter cette classe a ta balise nav (ou div). Lis la doc.

On a créé une classe .nav au lieu de le mettre directement sur le sélecteur
de balise nav pour que tu ne sois pas obligée d'avoir une nav préformatée,
si tu veux deux nav différentes par exemple, ou même si tu veux profiter
des autres avantages du framework mais pas la nav que tu trouve moche.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/simplonmars3/SimplonStrap/issues/2#issuecomment-263874990>,
or mute the thread
