### ISSUE TITLE
Problème doc

### ISSUE THREAD

**Issue by eukavlin** [simplonmars3/SimplonStrap#3]
Certaines parties ne sont pas à jour (je pense notamment à la partie "Barre de navigation" dont le code HTML n'est pas complet, et la partie grid où seule la flex grid apparaît dans la doc).

**Comment by valdiss** [comment]
HTML de la nav réglé, félix met en ligne la grid au plus vite.

**Comment by GLoSL** [comment]
C'est bon, grid mise en ligne.
