### ISSUE TITLE
Demande d'icones

### ISSUE THREAD

**Issue by Darkilen** [simplonmars3/SimplonStrap#4]
Bonjour,

A la suite de ce message, notez les icones dont vous aurez besoin. (Une personne par groupe svp)
Pour voir ce qui est disponible : http://fontello.com/

Date limite : 2 décembre à minuit

PS : Vérifiez qu'une personne avant vous ne l'a pas déjà demander ...

Merci d'avance !

**Comment by cams03** [comment]
Hello,
en ce qui nous concerne il faudrait l'icone du mail, twitter, facebook, html, css, js, jquery, C, php, github, linkedin, viadeo, telephone

Merci les gars !

**Comment by alexandradra** [comment]
[fontello-d47a62c0.zip](https://github.com/simplonmars3/SimplonStrap/files/624389/fontello-d47a62c0.zip)
Eh coucou ! 
Pour ma part j'ai besoin des icônes que je vous joins ici.
Pour le logo site web on hésite entre le trombone et la main, donc il faudrait que l'on teste les deux :)
Cimer !

**Comment by eukavlin** [comment]
Quand pourrons-nous avoir les icônes ?
Merci ! :)

**Comment by githly** [comment]
Le Dossier d'icones est a disposition sur le repo ! AMusez vous !
