### ISSUE TITLE
Cohérence de nommage

### ISSUE THREAD

**Issue by metallou** [simplonmars3/SimplonStrap#8]
Vous êtes pas cohérents
dans la partie "Flex properties":
vous avez défini dflexsp-b pour 'justify-content: space between'
MAIS vous avez défini dflex-a pour 'justify-content:space-around'

Aussi, vous avez des doublons (dflex et dflexcenter sont définis deux fois à 20lignes d'écarts)

Vous pouvez corriger ça ?

**Comment by metallou** [comment]
y'a aussi poabs[side][side] et poabs[side] qui sont sémantiquement pas cohérents
c'est pas cohérent de mettre up/down quand les propriétés css sont top/bottom
ça devient incohérent pour les angles ul pout topleft, ur pour topright, dl pour bottomleft, dr pour bottomright

**Comment by GLoSL** [comment]
Ajout et modification de classes et de nom de classes pour rendre l'ensemble plus cohérent.

Pour la suppression de certains noms de classes, il faudra se mettre d'accord pour que chacun modifie les noms de classes dans leurs trombis.
